version: "3.7"
services:
  proyectos-monolitica:
    container_name: proyectos-monolitica
    image: proyectos-monolitica:v1
    build: 
      context: .
    ports:
      - "4001:4001"
    networks:
      - proyectos-app
networks:
  proyectos-app: 